[package]
name = "bare-program"
version = "0.1.0"
edition = "2021"

[dependencies]
ulx3s-hal = { path = "../ulx3s-hal"}
panic-halt = "0.2.0"
riscv-rt = { version = "0.14.0"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
