MEMORY {
	sdram : ORIGIN = 0x40000000, LENGTH = 0x00010000
}

REGION_ALIAS("REGION_TEXT", sdram);
REGION_ALIAS("REGION_RODATA", sdram);
REGION_ALIAS("REGION_DATA", sdram);
REGION_ALIAS("REGION_BSS", sdram);
REGION_ALIAS("REGION_HEAP", sdram);
REGION_ALIAS("REGION_STACK", sdram);
